#ifndef NATURAL_LANG_PROCESS_SYNTATIC_ANALYSIS_H
#define NATURAL_LANG_PROCESS_SYNTATIC_ANALYSIS_H

#define ERROR 1
#define OK 0

extern int parseProgram();

#endif //NATURAL_LANG_PROCESS_SYNTATIC_ANALYSIS_H
